// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_API_KEY'] ?? '',
    appId: '1:826038227928:web:c422993cdd61bd8c0458ad',
    messagingSenderId: '826038227928',
    projectId: 'fit-me-42dbe',
    authDomain: 'fit-me-42dbe.firebaseapp.com',
    storageBucket: 'fit-me-42dbe.firebasestorage.app',
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY'] ?? '',
    appId: '1:826038227928:android:058cda20edafdb610458ad',
    messagingSenderId: '826038227928',
    projectId: 'fit-me-42dbe',
    storageBucket: 'fit-me-42dbe.firebasestorage.app',
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY'] ?? '',
    appId: '1:826038227928:ios:76e07ed66eff783c0458ad',
    messagingSenderId: '826038227928',
    projectId: 'fit-me-42dbe',
    storageBucket: 'fit-me-42dbe.firebasestorage.app',
    iosBundleId: 'com.example.fitme',
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_MACOS_API_KEY'] ?? '',
    appId: '1:826038227928:ios:76e07ed66eff783c0458ad',
    messagingSenderId: '826038227928',
    projectId: 'fit-me-42dbe',
    storageBucket: 'fit-me-42dbe.firebasestorage.app',
    iosBundleId: 'com.example.fitme',
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WINDOWS_API_KEY'] ?? '',
    appId: '1:826038227928:web:43937ded1164f13e0458ad',
    messagingSenderId: '826038227928',
    projectId: 'fit-me-42dbe',
    authDomain: 'fit-me-42dbe.firebaseapp.com',
    storageBucket: 'fit-me-42dbe.firebasestorage.app',
  );
}
